type ReceiptLine = { name: string; quantity: number; price: string; currency: "USDT" | "GRAM"; photo?: string };
type PaymentLink = { id: string; createdAt: string; expiresAt: string; title: string; amount: string; currency: "USDT" | "GRAM"; assets: Array<"USDT" | "GRAM">; products: ReceiptLine[]; note: string; message: string; oneTime: boolean; status: "Активне" | "Оплачено" | "Прострочено" };

const config = () => { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? { url, key } : null; };
const apiHeaders = (key: string, extra: HeadersInit = {}) => ({ apikey: key, Authorization: `Bearer ${key}`, ...extra });

async function locate(id: string) {
  const connection = config();
  if (!connection) throw new Error("Storage unavailable");
  const response = await fetch(`${connection.url}/rest/v1/acquiring_stores?select=account,businesses,products_by_business`, { headers: apiHeaders(connection.key), cache: "no-store" });
  if (!response.ok) throw new Error("Storage unavailable");
  const rows = await response.json() as Array<{ account: string; businesses: Array<{ name: string; logo?: string }>; products_by_business: Record<string, unknown> }>;
  for (const row of rows) { const store = row.products_by_business || {}; const links = store.linksByBusiness as Record<string, PaymentLink[]> | undefined; if (!links) continue; for (const [businessName, items] of Object.entries(links)) { const index = items.findIndex((item) => item.id === id); if (index >= 0) return { connection, row, store, businessName, index, link: items[index] }; }
  }
  return null;
}

export async function GET(_: Request, context: { params: Promise<{ id: string }> }) { try { const found = await locate((await context.params).id); if (!found) return Response.json({ error: "Посилання не знайдено" }, { status: 404 }); const business = found.row.businesses.find((item) => item.name === found.businessName); const expired = found.link.status === "Активне" && new Date(found.link.expiresAt).getTime() < Date.now(); return Response.json({ link: { ...found.link, status: expired ? "Прострочено" : found.link.status }, business: { name: found.businessName, logo: business?.logo } }, { headers: { "Cache-Control": "no-store" } }); } catch { return Response.json({ error: "Посилання тимчасово недоступне" }, { status: 503 }); } }

export async function POST(_: Request, context: { params: Promise<{ id: string }> }) { try { const found = await locate((await context.params).id); if (!found) return Response.json({ error: "Посилання не знайдено" }, { status: 404 }); if (found.link.status !== "Активне" || new Date(found.link.expiresAt).getTime() < Date.now()) return Response.json({ error: "Посилання вже недійсне" }, { status: 409 }); const links = found.store.linksByBusiness as Record<string, PaymentLink[]>; const nextLink = { ...found.link, status: "Оплачено" as const }; links[found.businessName] = [...links[found.businessName]]; links[found.businessName][found.index] = nextLink; const payments = (found.store.paymentsByBusiness as Record<string, unknown[]> | undefined) || {}; const existing = Array.isArray(payments[found.businessName]) ? payments[found.businessName] : []; payments[found.businessName] = [{ id: `P-${Date.now().toString().slice(-6)}`, createdAt: new Date().toISOString(), source: "Платіжне посилання", sourceName: "Платіжне посилання", status: "Оплачено", currency: found.link.currency, amount: found.link.amount, products: found.link.products }, ...existing]; found.store.linksByBusiness = links; found.store.paymentsByBusiness = payments; const response = await fetch(`${found.connection.url}/rest/v1/acquiring_stores?account=eq.${encodeURIComponent(found.row.account)}`, { method: "PATCH", headers: apiHeaders(found.connection.key, { "Content-Type": "application/json", Prefer: "return=minimal" }), body: JSON.stringify({ products_by_business: found.store, updated_at: new Date().toISOString() }) }); if (!response.ok) throw new Error("Save failed"); return Response.json({ ok: true, message: found.link.message }); } catch { return Response.json({ error: "Не вдалося підтвердити оплату" }, { status: 503 }); } }
