"use client";

import { useState } from "react";
import "./marketing-page.css";
import { MarketingFooter, MarketingHeader, MarketingMotion } from "./marketing-shell";

type Section = "features" | "how" | "cabinet" | "about" | "security" | "developers" | "pricing" | "faq";

const steps = [["01", "Вхід через QR", "Відкрийте Nezeriya Wallet, скануйте QR і підтвердьте вхід."], ["02", "Бізнес і товари", "Створіть бізнес та додайте каталог із фото."], ["03", "Приймання оплати", "Створіть термінал або платіжне посилання."], ["04", "Виплата", "Виводьте доступні кошти у підключений Nezeriya Wallet."]];
const faqs = [["Скільки часу займає реєстрація?", "Кілька секунд: відкрийте Nezeriya Wallet, скануйте QR і підтвердьте вхід."], ["Які активи можна приймати?", "USDT і GRAM. Для кожного бізнесу активи можна налаштувати окремо."], ["Як я отримую кошти?", "Платежі перевіряються через серверний гаманець Nezeriya. Доступні кошти виводяться у підключений Nezeriya Wallet."], ["Чому сесія діє 24 години?", "Це захист доступу. Після завершення сесії достатньо повторно сканувати QR у Nezeriya Wallet."]];

function EnterButton({ children = "Почати" }: { children?: string }) { return <a className="np-page-button" href="/acquiring?login=1">{children} <span>↗</span></a>; }
function SectionLead({ kicker, title, children }: { kicker: string; title: React.ReactNode; children?: React.ReactNode }) { return <div className="np-page-lead" data-reveal><p className="np-kicker">— {kicker}</p><h1>{title}</h1>{children && <p>{children}</p>}</div>; }

function Features() { return <><SectionLead kicker="МОЖЛИВОСТІ" title={<>Приймайте оплату так,<br /><em>як зручно бізнесу</em></>}>Термінал, платіжні посилання та інтеграція з сайтом ведуть до однієї історії платежів.</SectionLead><div className="np-page-cards np-payment-cards">{[["▦", "Термінал", "Застосунок на звичайному телефоні: продавець обирає товари, а клієнт платить через QR або Nezeriya NFC.", ["Каталог синхронізується з кабінетом", "Автоматичні чеки", "USDT і GRAM"]], ["↗", "Платіжні посилання", "Створюйте рахунки на довільну суму або з товарів у каталозі.", ["Одноразові та з терміном дії", "QR для клієнта", "Статус в історії платежів"]], ["⌘", "Інтеграція з сайтом", "Приймання замовлень з вашого сайту в єдиній історії платежів.", ["Статуси й чеки", "Баланс бізнесу", "API для інтеграції"]]].map(([icon,title,text,list],i)=><article key={String(title)} data-reveal data-delay={String(i+1)}><i>{icon}</i><h2>{title}</h2><p>{text}</p><ul>{(list as string[]).map(x=><li key={x}>↗ {x}</li>)}</ul></article>)}</div><section className="np-phone-block" data-reveal><div><p className="np-kicker">— ТЕРМІНАЛ У ТЕЛЕФОНІ</p><h2>Каса, що завжди<br />поруч</h2><p>Товари синхронізуються з кабінету. Після вибору позицій покажіть клієнту QR на головному екрані терміналу.</p><EnterButton>Створити бізнес</EnterButton></div><div className="np-phone-example" aria-label="Приклад екрана терміналу"><small>ПРИКЛАД ІНТЕРФЕЙСУ</small><b>Термінал Nezeriya Pay</b><span>Каталог і оплата доступні після входу.</span><button type="button">Показати QR</button></div></section></> }
function How() { return <><SectionLead kicker="ЯК ЦЕ ПРАЦЮЄ" title={<>Від входу до виплати —<br /><em>у чотири кроки</em></>}>Без паролів і зайвих форм: усе починається з Nezeriya Wallet.</SectionLead><ol className="np-page-steps">{steps.map(([n,t,d],i)=><li key={n} data-reveal data-delay={String(i)}><b>{n}</b><div><h2>{t}</h2><p>{d}</p></div></li>)}</ol><section className="np-flow" data-reveal><p className="np-kicker">— ШЛЯХ ПЛАТЕЖУ</p><div><span>Клієнт</span><i>→</i><span>Термінал або посилання</span><i>→</i><span>Перевірка платежу</span><i>→</i><span>Кабінет бізнесу</span></div></section></> }
function Cabinet() { const tabs=["Аналітика","Платежі","Термінали","Товари","Виплати","Розробникам","Налаштування"]; return <><SectionLead kicker="КАБІНЕТ БІЗНЕСУ" title={<>Усе про ваш бізнес<br /><em>в одному кабінеті</em></>}>Після входу ви працюєте з власними даними, платежами, товарами та виплатами.</SectionLead><section className="np-cabinet-preview" data-reveal><small>ПРИКЛАД ІНТЕРФЕЙСУ — НЕ РЕАЛЬНІ ДАНІ</small><header>{tabs.map((tab,i)=><span className={i===0?"active":""} key={tab}>{tab}</span>)}</header><div className="np-cabinet-empty"><b>Ваші дані зʼявляться тут</b><p>Це лише схема інтерфейсу. Після входу кабінет показує дані саме вашого бізнесу.</p></div></section><EnterButton>Відкрити кабінет</EnterButton></> }
function About() { return <><SectionLead kicker="ПРО НАС" title={<>Крипто-еквайринг, який<br /><em>зрозуміє будь-який бізнес</em></>}>Допомагаємо малому та середньому бізнесу приймати USDT і GRAM так само просто, як картку.</SectionLead><div className="np-principles">{[["01","Прозорість","Одна комісія 0,5% без щомісячної плати."],["02","Гроші під вашим контролем","Доступні кошти виводяться у ваш Nezeriya Wallet."],["03","Швидкий старт","Почніть з QR-входу та створення бізнесу."]].map(([n,t,d],i)=><article key={n} data-reveal data-delay={String(i)}><b>{n}</b><h2>{t}</h2><p>{d}</p></article>)}</div></> }
function Security() { return <><SectionLead kicker="БЕЗПЕКА" title={<>Кожен чек має<br /><em>зрозумілу перевірку</em></>}>Деталі платежу доступні в кабінеті: сума, комісія, статус, хеш транзакції та гаманець клієнта.</SectionLead><div className="np-security-grid">{[["✓","Перевірка суми","Статус показує, чи отримано повну суму та чи зараховано її на баланс."],["#","Хеш у чеку","Після мережевого підтвердження хеш зберігається разом з операцією."],["▤","Деталі товарів","У квитанції є позиції, кількість і вартість кожної." ]].map(([i,t,d],n)=><article key={t} data-reveal data-delay={String(n)}><b>{i}</b><h2>{t}</h2><p>{d}</p></article>)}</div><EnterButton>Відкрити кабінет</EnterButton></> }
function Developers() { return <><SectionLead kicker="РОЗРОБНИКАМ" title={<>Інтегруйте оплату<br /><em>у свій продукт</em></>}>Платіжні посилання, QR-коди, захищений вхід і єдина історія чеків та виплат.</SectionLead><section className="np-dev-block" data-reveal><div><h2>API Nezeriya Pay</h2><p>Реальні приклади інтеграції доступні в документації після авторизації в кабінеті.</p><EnterButton>Створити бізнес</EnterButton></div><pre><code><span>// API документація</span>{"\n"}POST /v1/payments{"\n"}{"\n"}<b>Підключіть свій бізнес,</b>{"\n"}<b>щоб переглянути доступні методи.</b></code></pre></section></> }
function Pricing() { const [amount,setAmount]=useState("100"); const parsed=Number(amount.replace(",",".")); const fee=Number.isFinite(parsed)?parsed*.005:0; return <><SectionLead kicker="ТАРИФ" title={<>Одна комісія.<br /><em>Без зайвих умов.</em></>}>0,5% з успішного платежу. Без щомісячної плати.</SectionLead><section className="np-pricing" data-reveal><article><b>0,5%</b><p>від суми успішного платежу</p><ul><li>USDT і GRAM</li><li>Термінали, посилання та сайт</li><li>Виплата у Nezeriya Wallet</li></ul></article><div><label htmlFor="amount">Сума платежу</label><input id="amount" inputMode="decimal" value={amount} onChange={(e)=>setAmount(e.target.value)} /><p>Комісія Nezeriya Pay <strong>{fee.toLocaleString("uk-UA",{maximumFractionDigits:6})}</strong></p><p className="np-small">Комісію TON сплачує Nezeriya Pay.</p></div></section><EnterButton>Почати</EnterButton></> }
function FAQ() { const [open,setOpen]=useState(0); return <><SectionLead kicker="FAQ" title={<>Відповіді на<br /><em>поширені питання</em></>}/><div className="np-faq">{faqs.map(([q,a],i)=><article className={open===i?"open":""} key={q} data-reveal><button type="button" onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}>{q}<b>+</b></button>{open===i&&<p>{a}</p>}</article>)}</div></> }

export function MarketingPage({ section }: { section: Section }) { const pages={features:<Features/>,how:<How/>,cabinet:<Cabinet/>,about:<About/>,security:<Security/>,developers:<Developers/>,pricing:<Pricing/>,faq:<FAQ/>}; return <main className="np-marketing np-public-page"><MarketingMotion/><MarketingHeader active={section}/><div className="np-page"><div className="np-wrap">{pages[section]}</div></div><MarketingFooter/></main>; }
