type Payout = { id: string; createdAt: string; amount: string; currency: "USDT" | "GRAM"; status: "В обробці" | "Підтверджується" | "Виконано"; wallet: string; transaction?: string; serverWallet?: string; business: string };
type Store = { payoutsByBusiness?: Record<string, Payout[]> };
type Row = { account: string; products_by_business: Store };
function config() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? { url, key } : null; }
function headers(key: string, extra: HeadersInit = {}) { return { apikey: key, Authorization: `Bearer ${key}`, ...extra }; }
function allowed(request: Request) { const secret = process.env.NEZERIYA_PAYMENT_CALLBACK_SECRET; return Boolean(secret) && request.headers.get("authorization") === `Bearer ${secret}`; }
async function locate(id: string, url: string, key: string) { const response = await fetch(`${url}/rest/v1/acquiring_stores?select=account,products_by_business`, { headers: headers(key), cache: "no-store" }); const rows = response.ok ? await response.json() as Row[] : []; for (const row of rows) { const store = row.products_by_business && typeof row.products_by_business === "object" ? row.products_by_business : {}; for (const [business, payouts] of Object.entries(store.payoutsByBusiness || {})) { const index = Array.isArray(payouts) ? payouts.findIndex((item) => item.id === id) : -1; if (index >= 0) return { row, store, business, index, payout: payouts[index] }; } } return null; }
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { if (!allowed(request)) return Response.json({ error: "Лише Nezeriya Wallet" }, { status: 403 }); const connection = config(); if (!connection) return Response.json({ error: "Сховище недоступне" }, { status: 503 }); const found = await locate((await context.params).id, connection.url, connection.key); if (!found || found.payout.status !== "В обробці") return Response.json({ error: "Заявка недійсна" }, { status: 404 }); return Response.json(found.payout, { headers: { "Cache-Control": "no-store" } }); }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { if (!allowed(request)) return Response.json({ error: "Лише Nezeriya Wallet" }, { status: 403 }); const body = await request.json().catch(() => ({})) as { action?: string; transaction?: string; serverWallet?: string }; const connection = config(); if (!connection) return Response.json({ error: "Сховище недоступне" }, { status: 503 }); const found = await locate((await context.params).id, connection.url, connection.key); if (!found) return Response.json({ error: "Заявка недійсна" }, { status: 409 }); const next = body.action === "reserve" && found.payout.status === "В обробці" ? { ...found.payout, status: "Підтверджується" as const } : body.action === "complete" && found.payout.status === "Підтверджується" && typeof body.transaction === "string" ? { ...found.payout, status: "Виконано" as const, transaction: body.transaction, serverWallet: typeof body.serverWallet === "string" ? body.serverWallet : undefined } : null; if (!next) return Response.json({ error: "Заявка вже обробляється або недійсна" }, { status: 409 }); const payouts = found.store.payoutsByBusiness || {}; payouts[found.business] = [...payouts[found.business]]; payouts[found.business][found.index] = next; found.store.payoutsByBusiness = payouts; const saved = await fetch(`${connection.url}/rest/v1/acquiring_stores?account=eq.${encodeURIComponent(found.row.account)}`, { method: "PATCH", headers: headers(connection.key, { "Content-Type": "application/json", Prefer: "return=minimal" }), body: JSON.stringify({ products_by_business: found.store, updated_at: new Date().toISOString() }) }); return saved.ok ? Response.json({ ok: true }) : Response.json({ error: "Не вдалося оновити заявку" }, { status: 503 }); }
